part of '../theme.dart';

class AppColors {
  static ColorScheme get scheme {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff23184f),
      surfaceTint: Color(0xff615690),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff453b72),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff3b103b),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff60325e),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff23194f),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff453b72),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff4e0002),
      onError: Color(0xffffffff),
      errorContainer: Color(0xff8c0009),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffdf8ff),
      onSurface: Color(0xff000000),
      onSurfaceVariant: Color(0xff25232b),
      outline: Color(0xff44414a),
      outlineVariant: Color(0xff44414a),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff312f36),
      inversePrimary: Color(0xfff0e9ff),
      primaryFixed: Color(0xff453b72),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff2e245a),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff60325e),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff471b46),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff453b72),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff2e245b),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffddd8e0),
      surfaceBright: Color(0xfffdf8ff),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff7f2fa),
      surfaceContainer: Color(0xfff1ecf4),
      surfaceContainerHigh: Color(0xffebe6ee),
      surfaceContainerHighest: Color(0xffe6e1e9),
    );
  }
}
